# Generated by Django 3.2.25 on 2024-06-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
